### ISSUE TITLE
access_generator.py

### ISSUE THREAD

**Issue by vvajdic** [splunkzilla/Splunk_TA_fit#2]
Should access_generator run ok on OSX?
I am getting this:
   CLIENT_ID = parser.get('Authentication', 'C_KEY')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'Authentication'

**Comment by splunkzilla** [comment]
Sorry for the late response. This is a personal project that I and a few others are working on, and we can't always answer as promptly as we would like.

The entirety of the TA was built and tested on OSX, so that shouldn't be an issue. By looking at the error message it looks like it may be either a setup or file write permissions issue. Can you please confirm that your **_$SPLUNK_HOME/etc/apps/Splunk_TA_fit/local_** directory has a file called _**appconfig.conf**_?

If you are missing this file, then it looks like the setup app step didn't complete correctly. If you are missing the local folder completely, this may be because of a documentation issue in the README. This is the most likely cause. 

Because this is part of a Github project I suppressed the creation of a local folder while synching the files to Github. This is so I don't inadvertently put my local configuration in a public forum. It looks like I forgot to document the step where a **_local_** folder needs to be created **_under $SPLUNK_HOME/etc/apps/Splunk_TA_fit/_** directory. If this folder is missing, then the setup has no where to write the file changes. To fix this, please create a local folder under $SPLUNK_HOME/etc/apps/Splunk_TA_fit/ and re run setup app under the manage apps link.

If the above doesn't fix the issue, please let me know so we may investigate further. If the above fix works, please let me know as well so I may modify the documentation when I have time. Sorry for the inconvenience.

**Comment by vvajdic** [comment]
Thanks for a quick reply.
I do have a local directory and appconfig.conf is there, what else could I try?

On March 26, 2016 at 11:56:43 AM, Justin Boucher (notifications@github.com) wrote:

Sorry for the late response. This is a personal project that I and a few others are working on, and we can't always answer as promptly as we would like.

The entirety of the TA was built and tested on OSX, so that shouldn't be an issue. By looking at the error message it looks like it may be either a setup or file write permissions issue. Can you please confirm that your $SPLUNK_HOME/etc/apps/Splunk_TA_fit/local directory has a file called appconfig.conf?

If you are missing this file, then it looks like the setup app step didn't complete correctly. If you are missing the local folder completely, this may be because of a documentation issue in the README. This is the most likely cause.

Because this is part of a Github project I suppressed the creation of a local folder while synching the files to Github. This is so I don't inadvertently put my local configuration in a public forum. It looks like I forgot to document the step where a local folder needs to be created under $SPLUNK_HOME/etc/apps/Splunk_TA_fit/ directory. If this folder is missing, then the setup has no where to write the file changes. To fix this, please create a local folder under $SPLUNK_HOME/etc/apps/Splunk_TA_fit/ and re run setup app under the manage apps link.

If the above doesn't fix the issue, please let me know so we may investigate further. If the above fix works, please let me know as well so I may modify the documentation when I have time. Sorry for the inconvenience.

**Comment by splunkzilla** [comment]
Can you please post a sanitized copy of your local/appconfig.conf and your default/appconfig.conf? Please remember to sanitize the data since it will have access to your personal Fitbit app data.

According to the error, it doesn't look like it can access your appconfig.conf file. By default it is supposed to look for local/appconfig.conf, then go to default/appconfig.conf if the local isn't found. I have reloaded this on a fresh OSX instance (virtual) and I haven't had any issues. So let's also rule out file permission issues, just to make sure. I have posted the file permissions from the new virtual instance.

```
jboucher-mbpr15:Splunk_TA_fit jboucher$ ls -l
total 24
-rw-r--r--   1 jboucher  1064778472   281 Dec 21 09:57 LICENSE.txt
-rw-r--r--   1 jboucher  1064778472  6606 Feb 19 08:51 README.md
drwxr-xr-x@  4 jboucher  1064778472   136 Dec 21 09:50 appserver
drwxr-xr-x  22 jboucher  1064778472   748 Feb 11 14:36 bin
drwxr-xr-x  13 jboucher  1064778472   442 Jan  7 14:31 default
drwxr-xr-x   5 jboucher  1064778472   170 Jan  7 14:31 local
drwxr-xr-x   4 jboucher  1064778472   136 Jan  7 14:31 metadata
drwxr-xr-x  12 jboucher  1064778472   408 Jan  5 12:07 static
jboucher-mbpr15:Splunk_TA_fit jboucher$ cd local/
jboucher-mbpr15:local jboucher$ ls -l
total 24
-rw-------  1 jboucher  1064778472    28 Jan  7 14:31 app.conf
-rw-------  1 jboucher  1064778472   241 Jan  7 14:31 appconfig.conf
-rw-r--r--  1 jboucher  1064778472  1816 Jan  5 16:22 inputs.conf
jboucher-mbpr15:local jboucher$ cd ../default
jboucher-mbpr15:default jboucher$ ls -l
total 88
-rw-r--r--  1 jboucher  1064778472   964 Jan  7 12:35 app.conf
-rwxr-xr-x  1 jboucher  1064778472   794 Jan  7 14:31 appconfig.conf
-rw-r--r--  1 jboucher  1064778472   375 Dec 21 10:19 authorize.conf
-rw-r--r--  1 jboucher  1064778472   339 Dec 21 10:19 eventtypes.conf
-rw-r--r--  1 jboucher  1064778472   408 Dec 21 10:19 indexes.conf
-rw-r--r--  1 jboucher  1064778472  2327 Jan  5 15:47 inputs.conf
-rw-r--r--  1 jboucher  1064778472   302 Dec 21 10:20 macros.conf
-rw-r--r--  1 jboucher  1064778472   869 Jan  5 15:56 props.conf
-rw-r--r--  1 jboucher  1064778472   159 Jan  6 11:24 restmap.conf
-rw-r--r--  1 jboucher  1064778472  1047 Jan  7 12:35 setup.xml
-rw-r--r--  1 jboucher  1064778472   302 Dec 21 10:20 transforms.conf
jboucher-mbpr15:default jboucher$ 


```

Thank you for your patience while we work out this issue for you.

Respectfully,
Justin Boucher

**Comment by vvajdic** [comment]
Thank you very much Justin, will try to do this again.

Also did not quite know what values to put in the Fitbit Application form below.
For example “Application Website”. “Organization Website”, Organization, "Callback URL”.

Application Name *

Description *

Application Website *

Organization *

Organization Website *

OAuth 1.0 Application Type (Deprecated) *
Notice: OAuth 1.0a is deprecated and will be removed in April 2016. New applications should useOAuth 2.0. Existing applications should upgrade. Desktop  Browser
OAuth 2.0 Application Type *
 Server  Client  Personal
Callback URL *

Default Access Type *
 Read & Write  Read-Only


On March 26, 2016 at 1:39:34 PM, Justin Boucher (notifications@github.com) wrote:

Can you please post a sanitized copy of your local/appconfig.conf and your default/appconfig.conf? Please remember to sanitize the data since it will have access to your personal Fitbit app data.

According to the error, it doesn't look like it can access your appconfig.conf file. By default it is supposed to look for local/appconfig.conf, then go to default/appconfig.conf if the local isn't found. I have reloaded this on a fresh OSX instance (virtual) and I haven't had any issues. So let's also rule out file permission issues, just to make sure. I have posted the file permissions from the new virtual instance.

jboucher-mbpr15:Splunk_TA_fit jboucher$ ls -l
total 24
-rw-r--r--   1 jboucher  1064778472   281 Dec 21 09:57 LICENSE.txt
-rw-r--r--   1 jboucher  1064778472  6606 Feb 19 08:51 README.md
drwxr-xr-x@  4 jboucher  1064778472   136 Dec 21 09:50 appserver
drwxr-xr-x  22 jboucher  1064778472   748 Feb 11 14:36 bin
drwxr-xr-x  13 jboucher  1064778472   442 Jan  7 14:31 default
drwxr-xr-x   5 jboucher  1064778472   170 Jan  7 14:31 local
drwxr-xr-x   4 jboucher  1064778472   136 Jan  7 14:31 metadata
drwxr-xr-x  12 jboucher  1064778472   408 Jan  5 12:07 static
jboucher-mbpr15:Splunk_TA_fit jboucher$ cd local/
jboucher-mbpr15:local jboucher$ ls -l
total 24
-rw-------  1 jboucher  1064778472    28 Jan  7 14:31 app.conf
-rw-------  1 jboucher  1064778472   241 Jan  7 14:31 appconfig.conf
-rw-r--r--  1 jboucher  1064778472  1816 Jan  5 16:22 inputs.conf
jboucher-mbpr15:local jboucher$ cd ../default
jboucher-mbpr15:default jboucher$ ls -l
total 88
-rw-r--r--  1 jboucher  1064778472   964 Jan  7 12:35 app.conf
-rwxr-xr-x  1 jboucher  1064778472   794 Jan  7 14:31 appconfig.conf
-rw-r--r--  1 jboucher  1064778472   375 Dec 21 10:19 authorize.conf
-rw-r--r--  1 jboucher  1064778472   339 Dec 21 10:19 eventtypes.conf
-rw-r--r--  1 jboucher  1064778472   408 Dec 21 10:19 indexes.conf
-rw-r--r--  1 jboucher  1064778472  2327 Jan  5 15:47 inputs.conf
-rw-r--r--  1 jboucher  1064778472   302 Dec 21 10:20 macros.conf
-rw-r--r--  1 jboucher  1064778472   869 Jan  5 15:56 props.conf
-rw-r--r--  1 jboucher  1064778472   159 Jan  6 11:24 restmap.conf
-rw-r--r--  1 jboucher  1064778472  1047 Jan  7 12:35 setup.xml
-rw-r--r--  1 jboucher  1064778472   302 Dec 21 10:20 transforms.conf
jboucher-mbpr15:default jboucher$  



Thank you for your patience while we work out this issue for you.

Respectfully,
Justin Boucher

**Comment by splunkzilla** [comment]
Although your Fitbit app won't fix the error you are receiving, I've had this same question from the testers that I worked with. The documentation of the Fitbit site isn't the best if you are new to creating API calls. Do you think I should add a section to the documentation on creating the Fitbit app? Here is a sample of the Fitbit app config that I used:

**Application Name:** Splunk_TA_fit
**Description:** Self-explanatory
**Application Website:** https://github.com/splunkzilla/Splunk_TA_fit _*Redirects back to this page_
**Organization:** Splunk
**Organization Website:** http://www.splunk.com _*Doesn't matter for our purposes_
**OAuth1:** Browser _*Not used anyway_
**OAuth2:** Personal _*Required for intraday info like heart rate_
**Callback URL:** http://127.0.0.1:8080 _*Must match a trailing slash if provided._
**Default Access Type:** Read-only _*Splunk will not be able to write to a Fitbit profile_

That should be all you need to move forward with the Fitbit app piece. Then you will receive your ClientID and Client Secret that is needed for the TA setup. Please let me know if you think that this information should be added to the documentation as well. Also, please keep me posted on the status of your issue, so I can either close or fix any issues.

Respectfully,
Justin Boucher

**Comment by vvajdic** [comment]
Thanks Justin,
The next issue I am seeing is this:
https://www.fitbit.com/oauth2/authorize?scope=activity+heartrate+location+nutrition+profile+settings+sleep+social+weight&redirect_uri=https%3A%2F%2Fapi.fitbit.com%2Foauth2%2Ftoken&response_type=code&client_id=xxxxxx

"The app you're trying to connect did not provide valid information to Fitbit. Please report this issue to them.

Developer information: invalid_request - Invalid redirect_uri parameter value”

Thanks for your help,
vlado

On March 27, 2016 at 12:22:39 AM, Justin Boucher (notifications@github.com) wrote:

Although your Fitbit app won't fix the error you are receiving, I've had this same question from the testers that I worked with. The documentation of the Fitbit site isn't the best if you are new to creating API calls. Do you think I should add a section to the documentation on creating the Fitbit app? Here is a sample of the Fitbit app config that I used:

Application Name: Splunk_TA_fit
Description: Self-explanatory
Application Website: https://github.com/splunkzilla/Splunk_TA_fit *Redirects back to this page
Organization: Splunk
Organization Website: http://www.splunk.com *Doesn't matter for our purposes
OAuth1: Browser *Not used anyway
OAuth2: Personal *Required for intraday info like heart rate
Callback URL: http://127.0.0.1:8080 *Must match a trailing slash if provided.
Default Access Type: Read-only *Splunk will not be able to write to a Fitbit profile

That should be all you need to move forward with the Fitbit app piece. Then you will receive your ClientID and Client Secret that is needed for the TA setup. Please let me know if you think that this information should be added to the documentation as well. Also, please keep me posted on the status of your issue, so I can either close or fix any issues.

Respectfully,
Justin Boucher

**Comment by splunkzilla** [comment]
It's the wrong redirect uri. You will need to put in something like http://127.0.0.1:8080 in your Fitbit app, and mirror that same information in the TA setup. For example:

**Fitbit Callback URL:** http://127.0.0.1:8080
**TA Setup App Callback URL:** http://127.0.0.1:8080
**_*Notice that no trailing slash was used at the end. They must match exactly, or you will see the same error again._**

The one you are submitting to Fitbit is https://api.fitbit.com, which redirects back to the Fitbit API and doesn't instantiate a full connection between Splunk and your Fitbit data. You can adjust this in your local/appconfig.conf and at https://dev.fitbit.com. Just make sure that the redirect URI is exactly the same in both places.

**Comment by vvajdic** [comment]
Thanks Justin,
I am using http://127.0.0.1:8080 and here is the exception I get:


Please enter code (from the URL you were redirected to): af246f5c2c918bb45a3b9be3c62a29b0db5e86a8
Traceback (most recent call last):
  File "access_generator.py", line 39, in <module>
    token = fit.GetAccessToken(access_code)
  File "/Applications/splunk632/etc/apps/Splunk_TA_fit-master/bin/fitbit.py", line 106, in GetAccessToken
    resp = requests.post(self.TOKEN_URL, data=params, headers=headers)
  File "/Applications/splunk632/etc/apps/Splunk_TA_fit-master/bin/requests-2.0.0-py2.7.egg/requests/api.py", line 88, in post
  File "/Applications/splunk632/etc/apps/Splunk_TA_fit-master/bin/requests-2.0.0-py2.7.egg/requests/api.py", line 44, in request
  File "/Applications/splunk632/etc/apps/Splunk_TA_fit-master/bin/requests-2.0.0-py2.7.egg/requests/sessions.py", line 357, in request
  File "/Applications/splunk632/etc/apps/Splunk_TA_fit-master/bin/requests-2.0.0-py2.7.egg/requests/sessions.py", line 460, in send
  File "/Applications/splunk632/etc/apps/Splunk_TA_fit-master/bin/requests-2.0.0-py2.7.egg/requests/adapters.py", line 358, in send
requests.exceptions.SSLError: [Errno 20] Not a directory


On March 27, 2016 at 9:26:40 AM, Justin Boucher (notifications@github.com) wrote:

It's the wrong redirect uri. You will need to put in something like http://127.0.0.1:8080 in your Fitbit app, and mirror that same information in the TA setup. For example:

Fitbit Callback URL: http://127.0.0.1:8080
TA Setup App Callback URL: http://127.0.0.1:8080
*Notice that no trailing slash was used at the end. They must match exactly, or you will see the same error again.

The one you are submitting to Fitbit is https://api.fitbit.com, which redirects back to the Fitbit API and doesn't instantiate a full connection between Splunk and your Fitbit data. You can adjust this in your local/appconfig.conf and at https://dev.fitbit.com. Just make sure that the redirect URI is exactly the same in both places.

**Comment by vvajdic** [comment]
Could it be the same as this:
http://stackoverflow.com/questions/35973137/sslerror-not-a-directory

Here are the token_url, params and headers for the requests.post call:

https://api.fitbit.com/oauth2/token

{'redirect_uri': 'http://127.0.0.1:8080', 'code': ‘xxxxxxxxxxxxxxxxx', 'client_id': ‘yyyyyy', 'grant_type': 'authorization_code’}

{'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': 'Basic MjI3UDJHOmY5ZDY4YTkyYzdjNDYwNTk5MjQ2NmEzZGU3OGU3MDZl’}

-------------------
Traceback (most recent call last):
  File "access_generator.py", line 39, in <module>
    token = fit.GetAccessToken(access_code)
  File "/Applications/splunk632/etc/apps/Splunk_TA_fit-master/bin/fitbit.py", line 109, in GetAccessToken
    resp = requests.post(self.TOKEN_URL, data=params, headers=headers)


On March 27, 2016 at 1:26:34 PM, vlado vajdic (vvajdic@gmail.com) wrote:

Thanks Justin,
I am using http://127.0.0.1:8080 and here is the exception I get:


Please enter code (from the URL you were redirected to): af246f5c2c918bb45a3b9be3c62a29b0db5e86a8
Traceback (most recent call last):
  File "access_generator.py", line 39, in <module>
    token = fit.GetAccessToken(access_code)
  File "/Applications/splunk632/etc/apps/Splunk_TA_fit-master/bin/fitbit.py", line 106, in GetAccessToken
    resp = requests.post(self.TOKEN_URL, data=params, headers=headers)
  File "/Applications/splunk632/etc/apps/Splunk_TA_fit-master/bin/requests-2.0.0-py2.7.egg/requests/api.py", line 88, in post
  File "/Applications/splunk632/etc/apps/Splunk_TA_fit-master/bin/requests-2.0.0-py2.7.egg/requests/api.py", line 44, in request
  File "/Applications/splunk632/etc/apps/Splunk_TA_fit-master/bin/requests-2.0.0-py2.7.egg/requests/sessions.py", line 357, in request
  File "/Applications/splunk632/etc/apps/Splunk_TA_fit-master/bin/requests-2.0.0-py2.7.egg/requests/sessions.py", line 460, in send
  File "/Applications/splunk632/etc/apps/Splunk_TA_fit-master/bin/requests-2.0.0-py2.7.egg/requests/adapters.py", line 358, in send
requests.exceptions.SSLError: [Errno 20] Not a directory


On March 27, 2016 at 9:26:40 AM, Justin Boucher (notifications@github.com) wrote:

It's the wrong redirect uri. You will need to put in something like http://127.0.0.1:8080 in your Fitbit app, and mirror that same information in the TA setup. For example:

Fitbit Callback URL: http://127.0.0.1:8080
TA Setup App Callback URL: http://127.0.0.1:8080
*Notice that no trailing slash was used at the end. They must match exactly, or you will see the same error again.

The one you are submitting to Fitbit is https://api.fitbit.com, which redirects back to the Fitbit API and doesn't instantiate a full connection between Splunk and your Fitbit data. You can adjust this in your local/appconfig.conf and at https://dev.fitbit.com. Just make sure that the redirect URI is exactly the same in both places.

**Comment by splunkzilla** [comment]
I wasn't able to get to this last night, but I've seen this error before. Not in this script, but in others that use the requests module. The egg file isn't loading properly on your system. This should be a relatively easy fix. You should be able to install requests be doing the following in the terminal:

`pip install requests`

What I don't know yet, is why there is such a disparity among the test systems. It may have something to do with OSX versioning or internal OS configuration, but my data set is too small to know for sure. I'm going to file this under a bug for now and update the documentation with a troubleshooting section for now until I have a larger dataset to identify the real issue. 

Thanks for all your patience while working this issue. Please let me know if this fix works for you so I can document it correctly. Also, just for fun, could you send me the output of the following commands:

```
uname -a
python --version
```

You can send those privately if you wish, but it should show anything sensitive, other than your hostname, if you reply back to this forum.

**Comment by vvajdic** [comment]
Thanks Justin,
Needed to run: sudo pip install -r requirements/base.txt

Now I have data in Splunk!


On March 28, 2016 at 2:57:51 AM, Justin Boucher (notifications@github.com) wrote:

I wasn't able to get to this last night, but I've seen this error before. Not in this script, but in others that use the requests module. The egg file isn't loading properly on your system. This should be a relatively easy fix. You should be able to install requests be doing the following in the terminal:

pip install requests

What I don't know yet, is why there is such a disparity among the test systems. It may have something to do with OSX versioning or internal OS configuration, but my data set is too small to know for sure. I'm going to file this under a bug for now and update the documentation with a troubleshooting section for now until I have a larger dataset to identify the real issue.

Thanks for all your patience while working this issue. Please let me know if this fix works for you so I can document it correctly. Also, just for fun, could you send me the output of the following commands:

uname -a
python --version

You can send those privately if you wish, but it should show anything sensitive, other than your hostname, if you reply back to this forum.
