### ISSUE TITLE
access_generator.py error on CentOS7

### ISSUE THREAD

**Issue by jtrucks** [splunkzilla/Splunk_TA_fit#3]
I'm doing this via CLI on a CentOS7 system. There is no GUI on the box. Therefore, it opens a browser (elinks, w3m or whatever) and hangs. It appears to go to the wrong URL sitting on something like:

https://www.fitbit.com/oauth2/authorize?scope=activity+heartrate+location+nutrition+profile+settings+sleep+social+weight&redirect_uri=http%3A%2F%2F127.0.0.1%28080&response_type=code&client_id=xxxxxx
(this is slightly off because I did part of this by hand above)

I then discover after installing and running on my laptop that the terminal browser does not appear to show me (or not obviously) the form to allow the access to then get the code needed.

In Safari I selected Allow and pasted the code it gave me into the script's prompt, and now I'm off to test the app.

**Comment by splunkzilla** [comment]
Did this workaround work for you? This is still in beta, and I haven't closed all the loops on this yet.

**Comment by jtrucks** [comment]
Yes!

Though now I’ve got to block off time to dive into why I’m going over the API rate limit an still get the most granular fidelity possible. I want to start using this for real analytics on my activities as well as for testing various visualization and data sciency things without using our stock Eventgen or customer data.

Thanks!
Jesse


Jesse Trucks, GCIA, GCUX-Gold
Minister of Magic
Splunk Inc.
Mobile: 608-347-3833
Email:   jtrucks@splunk.com<mailto:jtrucks@splunk.com>
San Francisco | Cupertino | London | Hong Kong | Washington D.C. | Seattle | Plano | Singapore | Munich | Tokyo

This message is intended only for the personal, confidential, and authorized use of the recipient(s) named above. If you are not that person,
you are not authorized to review, use, copy, forward, distribute or otherwise disclose the information contained in the message.

On Apr 25, 2016, at 07:32, Justin Boucher <notifications@github.com<mailto:notifications@github.com>> wrote:


Did this workaround work for you? This is still in beta, and I haven't closed all the loops on this yet.

**Comment by splunkzilla** [comment]
The rate limit issue is concerning if you want to do true analytics. However, I have added some limited customization to the data. In the default/appconfig.conf there is a time_delay feature. You can adjust the time_delay to -15 or something like that, then increase your inputs.conf stanza interval to the same amount.

You will still get the same data, it will just come over as a larger JSON block. But you should be able to use makemv in your SPL to split those out. Additionally, The rate limit is 150 requests per hour and maybe you can cut back on something else like the activity interval and time_delay to keep your heart rate information unmodified. Hope this helps.

**Comment by jtrucks** [comment]
Justin,

That should be perfect. I think it’s pulling the summaries and intraday every few minutes, so I can see how this could get me over the rate limit if I’m trying to pull too much. I’ll narrow it down more first, then perhaps see if I can monkey with the time_delay if needed.

Thanks!
Jesse


Jesse Trucks, GCIA, GCUX-Gold
Minister of Magic
Splunk Inc.
Mobile: 608-347-3833
Email:   jtrucks@splunk.com<mailto:jtrucks@splunk.com>
San Francisco | Cupertino | London | Hong Kong | Washington D.C. | Seattle | Plano | Singapore | Munich | Tokyo

This message is intended only for the personal, confidential, and authorized use of the recipient(s) named above. If you are not that person,
you are not authorized to review, use, copy, forward, distribute or otherwise disclose the information contained in the message.

On Apr 25, 2016, at 08:50, Justin Boucher <notifications@github.com<mailto:notifications@github.com>> wrote:


The rate limit issue is concerning if you want to do true analytics. However, I have added some limited customization to the data. In the default/appconfig.conf there is a time_delay feature. You can adjust the time_delay to -15 or something like that, then increase your inputs.conf stanza interval to the same amount.

You will still get the same data, it will just come over as a larger JSON block. But you should be able to use makemv in your SPL to split those out. Additionally, The rate limit is 150 requests per hour and maybe you can cut back on something else like the activity interval and time_delay to keep your heart rate information unmodified. Hope this helps.
