### ISSUE TITLE
hr.py is giving errors and not pulling down heart rate data.

### ISSUE THREAD

**Issue by roshepard** [splunkzilla/Splunk_TA_fit#4]
In trying to determine why I wasn't getting heart rate data, I noticed the following error in splunk.  Is there a time series specification that needs to be set?

04-24-2016 10:47:28.380 -0500 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/Splunk_TA_fit/bin/hr.py"     time_series = fit.TimeSeries('Heart')
04-24-2016 10:47:28.380 -0500 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/Splunk_TA_fit/bin/hr.py"   File "/opt/splunk/etc/apps/Splunk_TA_fit/bin/fitbit.py", line 219, in TimeSeries
04-24-2016 10:47:28.380 -0500 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/Splunk_TA_fit/bin/hr.py"     time_delay = parser.get(endpoint, 'TIME_DELAY')
04-24-2016 10:47:28.380 -0500 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/Splunk_TA_fit/bin/hr.py"   File "/opt/splunk/lib/python2.7/ConfigParser.py", line 618, in get
04-24-2016 10:47:28.382 -0500 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/Splunk_TA_fit/bin/hr.py"     raise NoOptionError(option, section)
04-24-2016 10:47:28.382 -0500 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/Splunk_TA_fit/bin/hr.py" ConfigParser.NoOptionError: No option 'time_delay' in section: 'Heart'
04-24-2016 10:48:28.675 -0500 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/Splunk_TA_fit/bin/hr.py" Traceback (most recent call last):
04-24-2016 10:48:28.675 -0500 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/Splunk_TA_fit/bin/hr.py"   File "/opt/splunk/etc/apps/Splunk_TA_fit/bin/hr.py", line 18, in <module>

**Comment by splunkzilla** [comment]
Looks like the default/appconfig.conf isn't being read correctly. This file should contain a [heart] stanza that contains the default configuration for this information. Can you please copy the information from this file to the local/appconfig.conf file created during your setup process?

This should give us more information on the potential issue that is occurring. Can you provide your OS information as well? Looks like it's either *nix or OSX, but python functions differently in both and this can help us narrow down the issue as well. Thank you in advance.

**Comment by roshepard** [comment]
You were correct.  The inputs.conf was lacking that one line for time_delay.  I added it and it started collecting the data as needed. Thanks!!
