### ISSUE TITLE
Question: Is there a technical reason that the Fitbit One can't work?

### ISSUE THREAD

**Issue by frankcharlton** [splunkzilla/Splunk_TA_fit#5]
Is there any way I could modify the project to get my Fitbit one working, or is the data formatted in a way that is unsupported?

**Comment by splunkzilla** [comment]
Delayed response due to work engagements:

It's just untested at this point. The data is all fed into Splunk via JSON rest calls, so their shouldn't be an issue. You will need to determine the right datasets to put in your inputs.conf file.
